{% set name = "loopy" %}
{% set version = "2025.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2de13505e2b3faa14917708e5eae1420e5eee19ba81bc46157c397292e9721e3

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - pytools >=2021.2.4
    - pymbolic >=2019.2
    - genpy >=2016.1.2
    - numpy >=1.19
    - cgen >=2016.1
    - islpy >=2019.1
    - codepy >=2017.1
    - colorama
    - mako
    - pyrsistent
    - pytest
    - immutables
    - constantdict

test:
  imports:
    - loopy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://mathema.tician.de/software/loopy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A code generator for array-based code on CPUs and GPUs'
  description: |
    Loopy lets you easily generate the tedious, complicated code that
    is necessary to get good performance out of GPUs and multi-core CPUs.
    Loopy's core idea is that a computation should be described simply
    and then transformed into a version that gets high performance. This
    transformation takes place under user control, from within Python.
  doc_url: http://mathema.tician.de/software/loopy
  dev_url: https://github.com/inducer/loopy

extra:
  recipe-maintainers:
    - inducer
    - jan-janssen
